#!/usr/bin/env bash
# CHANGELOG Generator
# Generates a structured CHANGELOG.md from git commit history
set -euo pipefail

OUTPUT_FILE="CHANGELOG.md"
RANGE=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        -o|--output) OUTPUT_FILE="$2"; shift 2 ;;
        *) RANGE="$1"; shift ;;
    esac
done

if [ -z "$RANGE" ]; then
    LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
    if [ -z "$LAST_TAG" ]; then
        RANGE="HEAD"
    else
        RANGE="${LAST_TAG}..HEAD"
    fi
fi

COMMITS=$(git log "$RANGE" --pretty=format:"%h|%s|%ad" --date=short 2>/dev/null || echo "")
if [ -z "$COMMITS" ]; then
    echo "No commits found for range: $RANGE"
    exit 0
fi

ADDED=()
FIXED=()
CHANGED=()
REMOVED=()
SECURITY=()
OTHER=()

while IFS='|' read -r hash subject date; do
    [ -z "$hash" ] && continue
    case "$subject" in
        feat:*|feature:*|new:*) ADDED+=("- $subject ($hash)") ;;
        fix:*|bugfix:*|patch:*) FIXED+=("- $subject ($hash)") ;;
        refactor:*|change:*|modify:*) CHANGED+=("- $subject ($hash)") ;;
        remove:*|delete:*|drop:*) REMOVED+=("- $subject ($hash)") ;;
        security:*|CVE-*|vulnerability:*) SECURITY+=("- $subject ($hash)") ;;
        *) OTHER+=("- $subject ($hash)") ;;
    esac
done <<< "$COMMITS"

{
echo "# Changelog"
echo ""
echo "## Changes since $RANGE"
echo ""
[ ${#ADDED[@]} -gt 0 ] && { echo "### Added"; printf '%s\n' "${ADDED[@]}"; echo ""; }
[ ${#FIXED[@]} -gt 0 ] && { echo "### Fixed"; printf '%s\n' "${FIXED[@]}"; echo ""; }
[ ${#CHANGED[@]} -gt 0 ] && { echo "### Changed"; printf '%s\n' "${CHANGED[@]}"; echo ""; }
[ ${#REMOVED[@]} -gt 0 ] && { echo "### Removed"; printf '%s\n' "${REMOVED[@]}"; echo ""; }
[ ${#SECURITY[@]} -gt 0 ] && { echo "### Security"; printf '%s\n' "${SECURITY[@]}"; echo ""; }
[ ${#OTHER[@]} -gt 0 ] && { echo "### Other"; printf '%s\n' "${OTHER[@]}"; echo ""; }
echo "---"
echo "*Generated by changelog.sh*"
} > "$OUTPUT_FILE"

echo "CHANGELOG generated: $OUTPUT_FILE"
echo "Added=${#ADDED[@]} Fixed=${#FIXED[@]} Changed=${#CHANGED[@]} Removed=${#REMOVED[@]} Security=${#SECURITY[@]} Other=${#OTHER[@]}"
